import type { ContextBridge } from "@common/ContextBridge";
import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld(
    "ContextBridge",
    <ContextBridge>{
        getServerStatus: () => ipcRenderer.invoke("app:getServerStatus"),
        isXenoInstalled: () => ipcRenderer.invoke("app:isXenoInstalled"),
        startServer: () => ipcRenderer.invoke("app:startServer"),
        stopServer: () => ipcRenderer.invoke("app:stopServer"),
        health: () => ipcRenderer.invoke("app:health"),
        getClients: () => ipcRenderer.invoke("app:getClients"),
        getRobloxProcesses: () => ipcRenderer.invoke("app:getRobloxProcesses"),
        attach: () => ipcRenderer.invoke("app:attach"),
        initDll: () => ipcRenderer.invoke("app:initDll"),
        getConfig: () => ipcRenderer.invoke("app:getConfig"),
        execute: (script, pids) => ipcRenderer.invoke("app:execute", script, pids),
        getLogs: () => ipcRenderer.invoke("app:getLogs"),
        getVersion: () => ipcRenderer.invoke("app:getVersion"),
        getServerVersionFile: () => ipcRenderer.invoke("app:getServerVersionFile"),
        checkServerUpdate: () => ipcRenderer.invoke("app:checkServerUpdate"),
        downloadServer: () => ipcRenderer.invoke("app:downloadServer"),
        downloadXeno: () => ipcRenderer.invoke("app:downloadXeno"),
        onServerDownloadProgress: (cb) => ipcRenderer.on("app:serverDownloadProgress", (_e, p) => cb(p)),
        onServerRetry: (cb) => ipcRenderer.on("app:serverRetry", (_e, data) => cb(data)),
        onXenoProgress: (cb) => ipcRenderer.on("app:xenoProgress", (_e, p) => cb(p)),
        onXenoRetry: (cb) => ipcRenderer.on("app:xenoRetry", (_e, data) => cb(data)),
        onServerDied: (cb) => ipcRenderer.on("app:serverDied", () => cb()),
        getXenoVersion: () => ipcRenderer.invoke("app:getXenoVersion"),
        saveAppState: (state) => ipcRenderer.invoke("app:saveState", state),
        loadAppState: () => ipcRenderer.invoke("app:loadState"),
        getXenoDir: () => ipcRenderer.invoke("app:getXenoDir"),
        getScriptsDir: () => ipcRenderer.invoke("app:getScriptsDir"),
        saveScript: (name, content) => ipcRenderer.invoke("app:saveScript", name, content),
        loadScripts: () => ipcRenderer.invoke("app:loadScripts"),
        deleteScript: (name) => ipcRenderer.invoke("app:deleteScript", name),
        searchScriptblox: (query, page) => ipcRenderer.invoke("scriptblox:search", query, page),
        trendingScriptblox: () => ipcRenderer.invoke("scriptblox:trending"),
        scriptbloxSource: (slug) => ipcRenderer.invoke("scriptblox:source", slug),
        onNativeThemeChanged: (cb) => ipcRenderer.on("nativeThemeChanged", (_e, dark) => cb(dark)),
        minimize: () => ipcRenderer.send("window:minimize"),
        maximize: () => ipcRenderer.send("app:toggleMaximize"),
        close: () => ipcRenderer.send("window:close"),
        isMaximized: () => ipcRenderer.invoke("app:isMaximized"),
        toggleMaximize: () => ipcRenderer.send("app:toggleMaximize"),
        setWindowSize: (width, height) => ipcRenderer.send("window:setSize", width, height),
        centerWindow: () => ipcRenderer.send("window:center"),
        getAppVersion: () => ipcRenderer.invoke("app:getAppVersion"),
        checkForAppUpdate: () => ipcRenderer.invoke("app:checkForAppUpdate"),
        downloadAppUpdate: (url, file) => ipcRenderer.invoke("app:downloadAppUpdate", url, file),
        installAppUpdate: (zipPath) => ipcRenderer.invoke("app:installAppUpdate", zipPath),
        restartApp: () => ipcRenderer.send("app:restartApp"),
        onAppUpdateProgress: (cb) => ipcRenderer.on("app:appUpdateProgress", (_e, p) => cb(p)),
    },
);
